version: '3.7'

services:
  app:
    image: node:16-alpine
    command: sh -c "npm install && npm run start:debug"
    ports:
      - 5000:5000
    working_dir: /app
    volumes:
      - ./:/app
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: rn-db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - mongo:/data/db

volumes:
  mongo:
    name: nest-mongodb
