version: '3.7'

services:
  app:
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
      - '/app/node_modules'
  db:
    image: mongo
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PWD}
    volumes:
      - mongo:/data/db

  redis:
    image: redis
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/data/redis

volumes:
  mongo:
    name: nest-mongodb
  redis:
    name: nest-redis
