version: '3.7'

services:
  app:
    image: node:16-alpine
    command: sh -c "npm install && npx prisma migrate dev && npm run start:debug"
    ports:
      - 5000:5000
      - 9229:9229
    working_dir: /app
    volumes:
      - ./:/app
  db:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    name: nest-db
